sudo: false

language: python

python:
  - 2.7
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements.txt

script:
  - python ./Demo/StatsModelsDemo.py
  - pytest  
