sudo: false

language: python

python:
  - 3.7

matrix:
  allow_failures:
    - python: nightly

install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade pandas
  - pip3 install --upgrade statsmodels
  - pip3 install --upgrade matplotlib
  - pip3 install --upgrade scipy
  - pip3 install --upgrade kafka
  - pip3 install --upgrade flair
  - pip3 install --upgrade tensorflow

script:
  - python ./demo/stats_models_demo.py
  - python ./test.py
  - python ./demo/numpy_demo.py
  - python ./web_spider/web_spider_file_utils.py
