sudo: false

language: python

python:
  - 2.7
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install --upgrade pip
  - pip install --upgrade pandas
  - pip install --upgrade statsmodels

script:
  - python ./Demo/StatsModelsDemo.py
  - pytest  
