sudo: false

language: python

python:
  - 2.7

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install --upgrade pip
  - pip install --upgrade pandas
  - pip install --upgrade statsmodels
  - pip install --upgrade matplotlib
  - pip install --upgrade scipy
  - pip install --upgrade kafka

script:
  - python ./demo/stats_models_demo.py
  - python ./test.py
  - python ./demo/numpy_demo.py
  - python ./web_spider/web_spider_file_utils.py
